package com.lyplay.sflow.orm;

import java.util.List;

import javax.annotation.Resource;

import org.apache.commons.lang3.ArrayUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import com.lyplay.sflow.orm.components.BatchUpdateSetter;
import com.lyplay.sflow.orm.components.Pagination;
import com.lyplay.sflow.orm.components.ReturnIdPreparedStatementCreator;
import com.lyplay.sflow.orm.components.SqlParamsPairs;
import com.lyplay.sflow.orm.exception.IdValueNotEqualsException;
import com.lyplay.sflow.orm.exception.NoIdAnnotationFoundException;
import com.lyplay.sflow.orm.exception.NoIdValueFoundException;
import com.lyplay.sflow.orm.utils.CommonRowMapper;
import com.lyplay.sflow.orm.utils.IdUtil;
import com.lyplay.sflow.orm.utils.ModelSqlUtil;
import com.lyplay.sflow.orm.utils.PagingUtil;
import com.lyplay.sflow.orm.utils.PoUtil;
import com.lyplay.sflow.orm.utils.PrintUtil;
import com.lyplay.sflow.orm.utils.ResultUtil;

@Repository("jdbcBaseDao")
public class JdbcBaseDAO<T> implements IBaseDAO<T>{
	
	private Logger logger = LoggerFactory.getLogger(this.getClass());
	
	@Resource
	private JdbcTemplate jdbcTemplate;
	
	
	@Override
	public Pagination<T> pageList(String sql, Object[] params, Class<T> clazz,
			Integer currentPage, Integer numPerPage) {
		
		Pagination<T> page = PagingUtil.getPagination(currentPage,numPerPage);
		
		try{
			
			StringBuffer totalSQL = new StringBuffer(" SELECT count(*) FROM ( ");
			totalSQL.append(sql);
			totalSQL.append(" ) totalTable ");
			PrintUtil.printErrSql(logger, totalSQL.toString(), params);
			page.setTotalRows(jdbcTemplate.queryForObject(totalSQL.toString(), params,Integer.class));
			
			page.setTotalPages();
			page.setStartIndex();
			page.setLastIndex();
			
			if (page.getCurrentPage() <= 1) {
				sql = PagingUtil.getPagingQuery(sql, false);
				params = ArrayUtils.add(params, params.length, page.getLastIndex());
			} else {
				sql = PagingUtil.getPagingQuery(sql, true);
				params = ArrayUtils.add(params, params.length, page.getLastIndex());
				params = ArrayUtils.add(params, params.length, page.getStartIndex());
			}
			
			PrintUtil.printErrSql(logger, sql, params);
			page.setResultList(jdbcTemplate.query(sql, params, new CommonRowMapper<T>(clazz)));
			
			return page;
			
		}catch(DataAccessException e){
			PrintUtil.printErrSql(logger, sql,params);
			throw e;
		}
		
	}
	
	
	@Override
	public boolean update(T po) {
		SqlParamsPairs sqlAndParams = null;
		try {
			sqlAndParams = ModelSqlUtil.getUpdateFromObject(po);
		} catch (Exception e) {
			logger.error(" Po class get update sql failed : {} ", po.getClass().getName());
			logger.error(e.getMessage(), e);
			throw new RuntimeException(e);
		}
		return update(sqlAndParams);
		
	}
	
	@Override
	public boolean batchUpdate(String sql,List<Object[]> paramsList){
		
		BatchUpdateSetter batchUpdateSetter = new BatchUpdateSetter(paramsList);
		
		try{
			PrintUtil.printDebugSql(logger, sql,paramsList);
			jdbcTemplate.batchUpdate(sql, batchUpdateSetter);
			return true;
		}catch(DataAccessException e){
			PrintUtil.printErrSql(logger, sql,paramsList);
			throw e;
		}
		
	}
	
	
	@Override
	public boolean save(T po) {
		try {
			String autoGeneratedColumnName = IdUtil.getAutoGeneratedId(po);
			if(!"".equals(autoGeneratedColumnName)){
				
				int idValue = save(po, autoGeneratedColumnName);
				
				IdUtil.setAutoIncreamentIdValue(po,autoGeneratedColumnName,idValue);
				
				return true;
			}else{
				SqlParamsPairs sqlAndParams = ModelSqlUtil.getInsertFromObject(po);
				return update(sqlAndParams);
			}
		} catch (Exception e) {
			logger.error(" save po object failed : {} ", po.getClass().getName());
			logger.error(e.getMessage(), e);
			throw new RuntimeException(e);
		}		
	}
	
	
	@Override
	public boolean delete(T po) {
		
		SqlParamsPairs sqlAndParams = null;
		try {
			sqlAndParams = ModelSqlUtil.getDeleteFromObject(po);
		} catch (Exception e) {
			logger.error(" delete po object failed : {} ", po.getClass().getName());
			logger.error(e.getMessage(), e);
			throw new RuntimeException(e);
		}
		return update(sqlAndParams);	
	}

	@Override
	public JdbcTemplate getJdbcTemplate() {
		return jdbcTemplate;
	}


	public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}


	@Override
	public boolean saveOrUpdate(T po) {
		
		if(po == null){
			return false;
		}
		
		SqlParamsPairs sqlAndParams = null;
		
		try {
			sqlAndParams = ModelSqlUtil.getLoadFromObject(po);
		} catch (NoIdAnnotationFoundException e) {
			logger.error(e.getMessage(), e);
		} catch (NoIdValueFoundException e) {
			logger.error(e.getMessage(), e);
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
		
		if(sqlAndParams != null){
			PrintUtil.printDebugSql(logger, sqlAndParams);
			Object existPo = ResultUtil.getFrist(jdbcTemplate.query(sqlAndParams.getSql(), sqlAndParams.getParams(), new CommonRowMapper<>(po.getClass())));
			if(existPo == null){
				return save(po);
			}else{
				boolean updateFlag = true;
				try {
					updateFlag = PoUtil.PoEquals(po, existPo);
				} catch (NoIdValueFoundException e) {
					logger.error(e.getMessage(), e);
				} catch (IdValueNotEqualsException e) {
					logger.error(e.getMessage(), e);
				} catch (Exception e) {
					logger.error(e.getMessage(), e);
				}
				
				if(updateFlag){
					logger.info(String.format("%s po value same as database value no need update now.",po.getClass().getName()));
					return true;
				}else{
					return update(po);
				}
				
			}
		}else{
			return this.save(po);
		}
	}

	
	private boolean update(SqlParamsPairs sqlAndParams){
		try{
			PrintUtil.printDebugSql(logger, sqlAndParams);
			return jdbcTemplate.update(sqlAndParams.getSql(), sqlAndParams.getParams()) > 0;
		}catch(DataAccessException e){
			PrintUtil.printErrSql(logger, sqlAndParams);
			throw e;
		}
	}

	private int save(T po, String autoGeneratedColumnName) throws Exception {

		SqlParamsPairs sqlAndParams = ModelSqlUtil.getInsertFromObject(po);

		return insert(sqlAndParams, autoGeneratedColumnName);
	}
	
	public int insert(SqlParamsPairs sqlAndParams,String autoGeneratedColumnName)
			throws DataAccessException{
		//dynamic change catalog name
		ReturnIdPreparedStatementCreator psc = new ReturnIdPreparedStatementCreator(sqlAndParams.getSql(), sqlAndParams.getParams(), autoGeneratedColumnName);
		KeyHolder keyHolder = new GeneratedKeyHolder();
		try{
			PrintUtil.printDebugSql(logger, sqlAndParams);
			jdbcTemplate.update(psc, keyHolder);
		}catch(DataAccessException e){
			PrintUtil.printErrSql(logger, sqlAndParams);
			throw e;
		}
		
		return keyHolder.getKey().intValue();
	}
	
}
